### ISSUE TITLE
DOM library declaration is required in tsconfig.json for a server-side application

### ISSUE THREAD

**Issue by xtazz** [bufbuild/connect-es#481]
**Describe the bug**

If the DOM library declaration is not included in `tsconifg.json`, then compilation fails in `connect-core` with the error:
```bash
node_modules/@bufbuild/connect-core/dist/types/call-options.d.ts (13:15)
13     headers?: HeadersInit;
                 ~~~~~~~~~~~
```

I would assume this type is only used for browser-side code so it would be great if it's possible to avoid adding DOM as a library for a server-side application.

**To Reproduce**
- Set up a TypeScript project which uses `connect-node` with `lib` option set to e.g. `["ESNext"]` in `tsconfig.json`.
- Try to compile it.

**Environment:**
- @bufbuild/connect-web version: `0.7.0`
- @bufbuild/connect-node version: `0.7.0`
- Frontend framework and version: N/A
- Node.js version: `18.14.0`
- Browser and version: N/A

**Comment by fubhy** [comment]
This is not just used in browser contexts. Fetch is also available in Node starting in Node v18+. Going forward, the right approach would be to correctly use the right types for the environment that you are targeting with your tsconfig.json. E.g. using `@types/node` (https://github.com/DefinitelyTyped/DefinitelyTyped) in the `types` field in tsconfig.json. Sadly, fetch is not included in there yet, hence DOM is your second best option (or using `@types/web` as a workaround).

**Comment by timostamm** [comment]
Hey Petr, @fubhy is on point here. 

The best available solution until this is resolved in @types/node appears to be the one noted by @meyfa in https://github.com/DefinitelyTyped/DefinitelyTyped/issues/60924#issuecomment-1246622957:

> As a workaround, I recommend [...] adding undici as a dev dependency and using the following adapted declaration:
> 
> ```ts
> declare global {
>   var fetch: typeof import('undici').fetch
> }
> ```

I'm going to close this issue because there is little we can do on our side, but will pin it for visibility, and hope that it will be helpful for other users. Thank you for raising it.

**Comment by xtazz** [comment]
@timostamm @fubhy, thanks for your input. I will try the workaround.
