### ISSUE TITLE
docs and generate code issue

### ISSUE THREAD

**Issue by tsingson** [bufbuild/connect-es#492]
**Describe the bug**

 in docs [https://connect.build/docs/web/generating-code](https://connect.build/docs/web/generating-code)
```
Output
Let's take a peek at what was generated. There are two new files:

gen/buf/connect/demo/eliza/v1/eliza_connect.ts
gen/buf/connect/demo/eliza/v1/eliza_pb.ts
The first file was generated by protoc-gen-connect-es and contains the service:

import { SayRequest, SayResponse } from "./eliza_pb.js";
import { MethodKind } from "@bufbuild/protobuf";
```

import { SayRequest, SayResponse } from "./eliza_pb.js"; 

should be 
```
import { SayRequest, SayResponse } from "./eliza_pb";
```
or
```
import { SayRequest, SayResponse } from "./eliza_pb.ts";
```

 

**Environment (please complete the following information):**
- @bufbuild/connect-web  0.7.0 / 0.8.0
- @bufbuild/connect   0.7.0 / 0.8.0

**Comment by timostamm** [comment]
If you want to write TypeScript with ECMAScript modules that works on Node.js and other environments, you have to use a `.js` extension in import paths to `.ts` files. See this [lengthy explanation](https://www.typescriptlang.org/docs/handbook/esm-node.html).

This is also reflected in the [code we generate](https://github.com/bufbuild/connect-es/blob/08f6d83f7cf2e2ca4b741b8e61c2e6d3a2daa84c/packages/example/src/gen/eliza_connect.ts#L20). You can change or remote the extension in generated import paths with [this option](https://github.com/bufbuild/connect-es/tree/main/packages/protoc-gen-connect-es#import_extensionjs) if you prefer.
