### ISSUE TITLE
@bufbuild/connect-node v0.8.2 is empty

### ISSUE THREAD

**Issue by fridolin-koch** [bufbuild/connect-es#514]
**Describe the bug**

I've upgraded `@bufbuild/connect-node` to `v0.8.2`, but it seems the distributed npm package is empty (i.e. no dist folder):

![image](https://user-images.githubusercontent.com/1880828/223360793-99a4b2e2-e67a-435a-9a26-24e524feac75.png)

![image](https://user-images.githubusercontent.com/1880828/223361186-8b401286-f4e6-4a0e-b980-3ba523f533cb.png)

vs. `v0.8.1`

![image](https://user-images.githubusercontent.com/1880828/223361609-dbf7f9cc-517c-408c-b9e0-ad51fa012f66.png)

**To Reproduce**

Install v0.8.2

**Environment (please complete the following information):**

N/A

**Additional context**

I guess something went wrong while building/publishing the package.

Kind regards,
Frido

**Comment by timostamm** [comment]
Thanks for the report, Frido!

I just published v0.8.2-1. You should be able to update with `npm i @bufbuild/connect-node@latest`.

**Comment by timostamm** [comment]
For the curious: This was caused by npm v9 changing how it parses its include/ignore lists, see https://github.com/bufbuild/connect-es/pull/521
