### ISSUE TITLE
Revisit types exports declaration

### ISSUE THREAD

**Issue by fubhy** [bufbuild/connect-es#524]
**Describe the bug**

I recently submitted a PR that moved the `types` declaration to the top in all package.json export declarations. It turns out that the TypeScript documentation is incorrect about this one and it probably shouldn't come first if we want to support CJS targeting consumers that are using NodeNext module resolution.

**Additional context**
Twitter thread: https://twitter.com/AndaristRake/status/1634508804728451072
Previous pull request: https://github.com/bufbuild/connect-es/commit/57b4e01d5ea517569732d0c4c478d19b52ffa0cb

**Comment by smaye81** [comment]
Can you clarify what the expected error would be or with what setup it should occur?  We tried testing this with a [CommonJS project](https://github.com/bufbuild/connect-es-integration/tree/main/react/webpack-cjs) we have in our Connect-ES Integration repo and it seems to work fine.  

We tried `NodeNext` in both `module` and `moduleResolution` and the app seems to be build and run fine.  Not sure if we're missing something in the test?

**Comment by fubhy** [comment]
I am not sure either tbh. but in that Twitter conversation it sounded like it wouldn't work under certain circumstances in a CJS context. So not sure what to do here. Just sit back and wait until someone complains in the future? Just wanted to bring this to your attention and was wondering if I had made a mistake with that change...

**Comment by fubhy** [comment]
Yep. And if that happens in the future we now have a breadcrumb to the cause already :)
