### ISSUE TITLE
error codes are not preserved

### ISSUE THREAD

**Issue by danielhochman** [bufbuild/connect-es#544]
**Describe the bug**

I am emitting an error from `connect-go` like so:
```go
connectgo.NewError(connectgo.CodeFailedPrecondition, errors.New("Service is disabled."))
```

The server is emitting the error correctly but when the [transport handler calls connectFromReason](https://github.com/bufbuild/connect-es/blob/8a8fdbd5970094397c2f74d5aad54ea67e47b4df/packages/connect-web/src/connect-transport.ts#L309), the `instanceof` check is failing and a new error is being created with the default code `Internal`.

See debugger output below. The error should have been returned on line 98 but instead the `instanceof` check fails and the code continues to create a new error.

![Screenshot from 2023-03-16 12-35-57](https://user-images.githubusercontent.com/4712430/225705648-4171f6fa-1bb1-4c89-9a3b-a3480bffe135.png)

Here are more details about the error:
![Screenshot from 2023-03-16 12-41-55](https://user-images.githubusercontent.com/4712430/225706796-19918510-2af7-4e76-b8e9-cc2b1c24cc56.png)

I did some research and from what I can tell this should ensure that we can correctly determine what the class is but it seems not to be working as expected: https://github.com/bufbuild/connect-es/blob/8a8fdbd5970094397c2f74d5aad54ea67e47b4df/packages/connect/src/connect-error.ts#L92

**Environment (please complete the following information):**

npm list
```npm list
├── @bufbuild/connect-web@0.8.3
├── @bufbuild/protobuf@1.1.0
├── @bufbuild/protoc-gen-connect-web@0.8.3
├── @bufbuild/protoc-gen-es@1.1.0
├── @parcel/config-webextension@2.8.2
├── @primer/octicons-react@17.12.0
├── @primer/octicons@17.12.0
├── @types/react-dom@18.0.10
├── @types/react@18.0.26
├── @types/webextension-polyfill@0.9.2
├── @typescript-eslint/eslint-plugin@5.48.0
├── @typescript-eslint/parser@5.48.0
├── assert@2.0.0
├── axios@1.2.2
├── babel-plugin-macros@3.1.0
├── buffer@6.0.3
├── delay@5.0.0
├── dom-loaded@3.0.0
├── element-ready@6.2.1
├── eslint-config-airbnb@19.0.4
├── eslint-config-preact@1.3.0
├── eslint-config-prettier@8.6.0
├── eslint-plugin-prettier@4.2.1
├── eslint@8.31.0
├── github-url-detection@6.1.0
├── jwt-decode@3.1.2
├── lightningcss@1.19.0
├── os-browserify@0.3.0
├── parcel@2.8.2
├── path-browserify@1.0.1
├── prettier@2.8.1
├── process@0.11.10
├── react-dom@18.2.0
├── react-timeago@7.1.0
├── react-tooltip@5.8.3
├── react@18.2.0
├── select-dom@7.1.1
├── styletron-engine-atomic@1.5.0
├── styletron-engine-monolithic@1.0.0
├── styletron-react@6.1.0
├── styletron@3.0.4
├── typescript@4.9.4
├── util@0.12.5
├── web-ext@7.4.0
├── webext-base-css@1.4.3
├── webext-options-sync@4.0.0
└── webextension-polyfill@0.10.0
```

- Node.js version: v18.14.2
- Browser and version: Google Chrome 111.0.5563.64

**Comment by danielhochman** [comment]
I just noticed a new release and tried the new versions but still not working.
```
├── @bufbuild/connect-web@0.8.4
├── @bufbuild/protobuf@1.1.1
├── @bufbuild/protoc-gen-connect-web@0.8.4
├── @bufbuild/protoc-gen-es@1.1.1
```

**Comment by smaye81** [comment]
Hi @danielhochman.  Could you provide a few more details about your environment?  For example:

- It looks like you're using Parcel as your bundler, correct? Are you using any other Parcel / Babel presets? It seems like you are not, but just wanted to confim.
- Can you share your `tsconfig.json` file?
- Also can you share how you are building your application?  i.e. is it something like `npx tsc && parcel build src/index.html`

Trying to track this error down and have been unable to recreate it locally thus far.

**Comment by danielhochman** [comment]
tsconfig.json
```json
{
  "compilerOptions": {
    "jsx": "react",
    "target":"es2022",
    "moduleResolution": "node",
    "types": ["react/next", "react-dom/next"]
  },
  "include": ["source/*.ts*"],
  "exclude": ["node_modules/**/*"]
}
```

.parcelrc
```json
{
	"extends": "@parcel/config-webextension"
}
```

build command (this is a browser extension)
```bash
parcel build source/manifest.json
```
