### ISSUE TITLE
ConnectError: [unknown] stream.getReader is not a function

### ISSUE THREAD

**Issue by ericvicenti** [bufbuild/connect-es#592]
**Describe the bug**

I see this error coming from "@bufbuild/connect-web". After reading the following code I suspect that the issue is "body" is missing from the response entirely and our GRPC server is not behaving correctly.

https://github.com/bufbuild/connect-es/blob/ca5c602ce8f859851a955c1110fa24247ae1f971/packages/connect/src/protocol/envelope.ts#L62

https://github.com/bufbuild/connect-es/blob/ca5c602ce8f859851a955c1110fa24247ae1f971/packages/connect-web/src/grpc-web-transport.ts#L170-L172

**Workaround**

Basically the only expected fix is to throw a helpful error that explains the server's mistake

```ts
const loggingInterceptor: Interceptor = (next) => async (req) => {
  try {
    return await next(req)
  } catch (e) {
    let error = e
    if (e.message.match('stream.getReader is not a function')) {
      error = new Error('GRPC Response Empty.')
    }
    throw error
  }
}
export const transport = createGrpcWebTransport({
  interceptors: [fixInterceptor]
});
```

**To Reproduce**

I'm not sure but I think this will happen when the GRPC server *incorrectly* sends no body in the response

**Environment (please complete the following information):**
```
    "@bufbuild/connect-web": "0.7.0",
    "@bufbuild/protobuf": "1.0.0",
```

**Comment by dimitropoulos** [comment]
hi @ericvicenti.  I've just looked into this and from what I can tell there's already a check ([here](https://github.com/bufbuild/connect-es/blob/ca5c602ce8f859851a955c1110fa24247ae1f971/packages/connect-web/src/grpc-web-transport.ts#L168)) that will throw a `missing response body` error if `response.body` is falsey.

Although it [used to be the case](https://github.com/gridscale/gsclient-js/issues/5) that the browser fetch's Response object didn't have a `getReader` method (back then, you [had to](https://github.com/gridscale/gsclient-js/commit/f6ebe20ac1886dc75411a22822b6cd7464c6b166#diff-5213657744683e71e4a7f6378da2d13f7a44260306cf1cd0179ad893a87d6d92R118) use [`Response.text()`](https://developer.mozilla.org/en-US/docs/Web/API/Response/text) instead) it seems like `ReadableStream.getReader()` has been [around for a while](https://developer.mozilla.org/en-US/docs/Web/API/ReadableStream/getReader) in browsers, with firefox being the last to pick it up in January 2019.

Just in case it's related: what browser (and version of that browser) are you seeing this error in?  I wonder if that could be related.  At least it would explain why `response.body` is present, but the `getReader` function is missing.

---

Also, are you able to help get a minimal testing setup for this so we can try to replicate?  I tried to write a failing test, but couldn't get it to fail in the way you're describing.

**Comment by timostamm** [comment]
Closing this. We're happy to reopen the issue if it's happening for any relevant browser.
