### ISSUE TITLE
[connect-fastify] status code always return 200

### ISSUE THREAD

**Issue by felangga** [bufbuild/connect-es#596]
**Describe the bug**

I enjoying created a gRPC server using Fastify and Bufbuild plugin `connect-fastify`.
It works perfectly, but I have a problem with the return status code. 
This `uRes.status` is always 200 even when I throw an error inside the routes routine. 
https://github.com/bufbuild/connect-es/blob/f6bafee56893eb35a3c60a4d6ed00696bf88af02/packages/connect-fastify/src/fastify-connect-plugin.ts#L86

It makes my Datadog status trace always OK (200), but it isn't. 

**To Reproduce**

I follow the tutorial from here https://connect.build/docs/node/getting-started
It covers the integration between Fastify and Bufbuild.
Then I add error throwing code to the router code to make the routine return error 
```import { ConnectRouter } from "@bufbuild/connect";
import { ElizaService } from "./gen/eliza_connect";
import { Code, ConnectError } from "@bufbuild/connect";

export default (router: ConnectRouter) =>
  // registers buf.connect.demo.eliza.v1.ElizaService
  router.service(ElizaService, {
    // implements rpc Say
    async say(req) {
     throw new ConnectError("test", Code.FailedPrecondition);
      return {}
    },
  });
```
**Environment (please complete the following information):**
- @bufbuild/connect-fastify version: 0.8.6
- fastify: 4.17.0
- Node.js version: 18.14.2

**Comment by timostamm** [comment]
Hey Felix, this is how gRPC works - every response has a HTTP status code 200, and error codes are transmitted in the HTTP trailers. See the [spec here](https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md#responses). There are trailers-only responses, but not every gRPC implementation uses them.

This is one downside that motivated us to add the [Connect protocol](https://connect.build/docs/protocol). For unary RPCs, the status is always reflected in the HTTP status code.
