### ISSUE TITLE
Updating Proto definitions on the server side breaks client

### ISSUE THREAD

**Issue by majst01** [bufbuild/connect-es#613]
**Describe the bug**

We updated the proto definition of our API as such that one message contains a additional field like so:

before:
```proto
message A {
  string name = 1;
}
```
after:
```proto
message A {
  string name = 1;
  string description = 2;
}
```

Updating the server side first and not updating the client side (react based) leads to the following error:

```
ConnectError: [invalid_argument] cannot decode message api.v1.A from JSON: key "description" is unknown
    at LN (connect-error.js:102:16)
    at parse (serialization.js:114:23)
```

Which breaks the client.

Is there any way to make the client side behave like the go deserializer to simply ignore unknown properties ?

**Environment (please complete the following information):**
- @bufbuild/connect version: (for example, `0.8.6`)
- @bufbuild/connect-web version: (for example, `0.8.6`)
- @bufbuild/connect-go version: (for example, `1.7.0`) (on the server side)
- Frontend framework and version: (for example, `react@18.2.0`)

**Comment by timostamm** [comment]
Hey @majst01, you can set JSON options on the Transport: 

https://github.com/bufbuild/connect-es/blob/29dc336bff2246044a9ac331ee70fedcfdcfa46c/packages/connect-web/src/connect-transport.ts#L96-L99

You'll want to set it as `{ ignoreUnknownFields: true }`, following the [definition here](https://github.com/bufbuild/protobuf-es/blob/a1a77e47f882a7756fda969e64656bea8e379945/packages/protobuf/src/json-format.ts#L79-L95).

We'll add this to the documentation on [connect.build](https://connect.build/), thanks for opening the issue!

**Comment by majst01** [comment]
This was fast, thanks a lot @timostamm
