### ISSUE TITLE
Switching from Graphql to Grpc is very painful without using basic functionality like "a field is required or optional" and without using FieldMask

### ISSUE THREAD

**Issue by frederikhors** [bufbuild/connect-es#621]
First of all: congratulations about this amazing project!

I coming to grpc from GraphQL where I can select fields (and relative sub-fields) easily omitting or adding what I need.

This along with the "default value" way of protobuf makes the transition from GraphQL a little hard for me: it's me there to decide which field is mandatory, which is optional and what fields I want from the backend.

From what I've read I understand that this is possibly done in protobuf with [FieldMask](https://netflixtechblog.com/practical-api-design-at-netflix-part-1-using-protobuf-fieldmask-35cfdc606518).

Good, but if I add them in my proto files I don't have any typing guarantees in typescript, right?

Example:

```proto
message Player {
  google.protobuf.FieldMask field_mask = 1;
  string id = 2;
  google.protobuf.Timestamp created_at = 3;
  string email = 4;
  string name = 5;
}
```

connect is generating:

```ts
export class Player extends Message<Player> {
  /**
   * @generated from field: google.protobuf.FieldMask field_mask = 1;
   */
  fieldMask?: FieldMask;

  // ...

  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "field_mask", kind: "message", T: FieldMask },
    { no: 2, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "created_at", kind: "message", T: Timestamp },
    { no: 4, name: "email", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);
  
  // ...
}
```

Even if I put it on the request message is the same: no typings:

```proto
message PlayerByIdReq {
  string id = 1;
  google.protobuf.FieldMask field_mask = 2;
}
```

This is obviously error prone because the schema can change and the field_mask are simple strings in their daily usage:

```ts
const res = await client.playerById({
  id: '123',
  fieldMask: { paths: ['name', 'email'] }
});
```

Am I wrong in this? Is there something I'm missing?

Thank you again for your commitment.

**Comment by marekbuild** [comment]
@frederikhors We have recently released https://github.com/bufbuild/knit, which allows you to do such field selection and other GraphQL like things. I'd love to pick your mind on what you are looking for and what a good solution looks like for you. Are you on the Buf public Slack?

**Comment by frederikhors** [comment]
@marekbuild thank you. Amazing project. Unfortunately I wanna build a Rust backend. Not golang. :(

**Comment by marekbuild** [comment]
@frederikhors Actually, Knit can be used with Rust backends. The Knit documentation just uses Go in examples, but there is nothing specific about Knit and Go, you can use Rust to write your backends which speak normal gRPC or gRPC-web.

You could get your type-safety and field masking if you used Knit for your client and deployed the [Knit gateway](https://github.com/bufbuild/knit/tree/main/tutorial/starwars-knit-gateway-standalone) (which is just a binary not a lib), and you could still have all your backends in Rust.

I'd be happy to put together an example repo if you want, just pass along any relevant details that should be in the example.

**Comment by frederikhors** [comment]
Thank you. Unfortunately we don't want to deploy anything we don't build ourself. So Knit gateway is not an option.
