### ISSUE TITLE
connect-web npm not found

### ISSUE THREAD

**Issue by pmzi** [bufbuild/connect-es#631]
**Describe the bug**

Our project is using https://www.npmjs.com/package/@bufbuild/connect-web but it gives 404 not found! Where did the package go?

**To Reproduce**

If you encountered an error message, please copy and paste it verbatim.
If the bug is specific to an RPC or payload, please provide a reduced
example.

**Environment (please complete the following information):**
- @bufbuild/connect-web version: (for example, `0.1.0`)
- @bufbuild/connect-node version: (for example, `0.1.0`)
- Frontend framework and version: (for example, `react@18.2.0`)
- Node.js version: (for example, `18.0.0`)
- Browser and version: (for example, `Google Chrome 103.0.5060.134`)

If your problem is specific to bundling, please also provide the following information: 

- Bundler and version: (for example, `webpack@5.74.0`)
- Bundler plugins and version: (for example `compression-webpack-plugin@10.0.0`)
- Bundler configuration file: 
```js

```

**Additional context**

**Comment by figueiredo2021** [comment]
Same issue here. [@bufbuild/connect](https://www.npmjs.com/package/@bufbuild/connect) seems to be unavailable at this moment.

**Comment by pmzi** [comment]
It seems like it is back. What was the problem? NPM is announcing an incident in their services. Is this because of that?

**Comment by figueiredo2021** [comment]
@pmzi

Apparently yes.

(From: https://status.npmjs.org/incidents/drj38qn6qm59?u=f4sjg6kgnfjh)
> This incident affects: www.npmjs.com website, Package installation, and Package publishing.
