### ISSUE TITLE
Incorrect error message when using `createRouterTransport`

### ISSUE THREAD

**Issue by srikrsna-buf** [bufbuild/connect-es#650]
The following test passes:
```ts
import {
  Code,
  ConnectError,
  createPromiseClient,
  createRouterTransport,
} from "@bufbuild/connect";
import { expect, test } from "@jest/globals";
import { ElizaService } from "@buf/bufbuild_eliza.bufbuild_connect-es/buf/connect/demo/eliza/v1/eliza_connect.js";

test("connect-error", () => {
  const transport = createRouterTransport(({ service }) => {
    service(ElizaService, {
      say: () => {
        throw new ConnectError("Foo", Code.Internal);
      },
    });
  });
  const elizaClient = createPromiseClient(ElizaService, transport);
  elizaClient.say({}).catch((error: ConnectError) => {
    expect(error.message).toMatchInlineSnapshot(`"[internal] Foo"`);
  });
});
```

The message received by the client should just be `Foo` but instead it has the `[code] ` prefix. I haven't verified using a regular transport.

**Environment (please complete the following information):**
-  `@buf/bufbuild_eliza.bufbuild_connect-es`: `0.8.6-20221224180530-f3801d450ef9.1`
-  `@bufbuild/connect`: `0.8.6`,
-   `@bufbuild/protobuf`: `1.2.0`
- `jest`: `29.5.0`
- `node`:  `19.6.0`

**Comment by timostamm** [comment]
It's a feature :blush:

https://github.com/bufbuild/connect-es/blob/a3c554847a927f53237ac4f3fc73b7856794bfbc/packages/connect/src/connect-error.ts#L30-L32

https://github.com/bufbuild/connect-es/blob/a3c554847a927f53237ac4f3fc73b7856794bfbc/packages/connect/src/connect-error.ts#L59-L62
