### ISSUE TITLE
Inconsistency with grpc-web handling errors (ignoring grpc-status header)

### ISSUE THREAD

**Issue by kostyay** [bufbuild/connect-es#652]
**Describe the bug**

We switched from using grpc-web to connect-web with grpc-web protocol.

Our backend returns the following response for errors, its HTTP 204 and two headers `grpc-status` and `grpc-message`:
```
< HTTP/2 204
< date: Thu, 25 May 2023 10:34:42 GMT
< grpc-status: 16
< grpc-message: unauthenticated
```

Native grpc-web implementation is able to parse this response properly returning the correct error code and message as extracted from the headers.

It appears that the connect-web grpc web transport implementation relies on http status codes and translates it into grpc status code ignoring the grpc-status/grpc-message headers.

**To Reproduce**

Create a web server that returns the following headers:
```javascript
app.get('/error', (req, res) => {
  res.set('grpc-status', '16');
  res.set('grpc-message', 'unauthenticated');
  res.sendStatus(204);
});
```

Make a call from grpc-web client, you will get error code 16. Make a call from connect-web with grpc-web transport you will get code 2 unknown.

**Comment by timostamm** [comment]
Hey Kostya, the gRPC-web protocol is specified [here](https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-WEB.md). The main difference to gRPC is that trailers are encoded as part of the response body, using the gRPC message framing with a special flag. The behavior regarding HTTP status codes in gRPC-web is inherited from the [gRPC protocol spec](https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md). 

Usually, the status is sent as a `grpc-status` field in the trailer, but for calls that produce an immediate error, servers may respond with a "Trailers-Only" response. Here is an example for a Trailers-Only response:

```
:status = 200
content-type = application/grpc+proto
grpc-status = 16
grpc-message = unauthenticated
```

Note that content-type is mandatory, and only status 200 is defined. I may be missing a bit here, but it looks to me that the response doesn't comply with the spec. Would you mind sharing what server that is?

If we don't see a status 200 and a recognized content-type, we map HTTP status codes to gRPC error codes. This is in accordance with the spec:

> Implementations should expect broken deployments to send non-200 HTTP status codes in responses as well as a variety of non-GRPC content-types and to omit Status & Status-Message. Implementations must synthesize a Status & Status-Message to propagate to the application layer when this occurs.

The mapping is defined [here](https://github.com/grpc/grpc/blob/master/doc/http-grpc-status-mapping.md).

**Comment by timostamm** [comment]
To clarify, we absolutely want to make our client more lenient for better interop if this response shape is common. 
We just need to make sure that this _is_ a common shape 🙂

**Comment by kostyay** [comment]
based on the quoted text you commented from the spec

> Implementations should expect broken deployments to *send non-200 HTTP status codes* in responses as well as a variety of non-GRPC content-types and to omit Status & Status-Message. Implementations must synthesize a Status & Status- Message to propagate to the application layer when this occurs.

I am reading it as non-200 http status codes meaning codes that are not part of the 200 family, eg 300/400 etc
I think 204 should be treaded as a 200 status code.

**Comment by timostamm** [comment]
Yes, per the protocol, the server _always_ uses a HTTP 200 status code, even in case of an immediate error.

I agree that a HTTP 204 is a good fit for a response without a body. But in your case, wouldn't it be preferable to reply with a HTTP 401? If you do, a [grpc-web](https://www.npmjs.com/package/grpc-web) client will map it to the gRPC code UNAUTHENTICATED. Our implementation does it too.

If you want to provide a valid gRPC-web response, I highly recommend to always use HTTP 200, and include the Content-Type response header as well. We are updating the gRPC-web client to be more lenient in https://github.com/bufbuild/connect-es/pull/656, but other implementations might not handle it as expected.

**Comment by kostyay** [comment]
Thanks for fixing this btw

**Comment by cvolante54** [comment]
Hi @timostamm. I'm running into a similar issue using envoy grpc-web filter. The error response from my service is a 200 with the Grpc-message and Grpc-status headers (as seen on the screenshot below). Are there any workaround for this? the envoy filter does not allow me to change the response status code for errors.
<img width="787" alt="Screenshot 2023-08-14 at 8 18 54 PM" src="https://github.com/bufbuild/connect-es/assets/28110819/4b5ef6aa-a072-4a2c-9936-d05a203b4e5d">

**Comment by timostamm** [comment]
Hey @cvolante54, it looks like you are running into a different issue. The root cause above was that we ignored the protocol-specific grpc-status header for a response that's out of protocol (no content-type header, non-200 HTTP status). 

Your response is a perfectly valid trailers-only response, and I am quite sure that we handle it properly. Can you double check that you set the necessary CORS headers? If the problem persists, please feel free to open a new issue with details to reproduce.
