### ISSUE TITLE
Support `baseUrl` is function instead `string` in ConnectTransportOptions

### ISSUE THREAD

**Issue by vctqs1** [bufbuild/connect-es#678]
**Is your feature request related to a problem? Please describe.**
As currently, my application have dynamic `baseUrl` based on few conditionals. Could we have support to pass `baseUrl` as function instead plain text 
(I'm willing to contribute to connect-es source if this is possible to do that without any negative side effect)

**Describe the solution you'd like**
Let look example below
```
const transport = createGrpcWebTransport({
  baseUrl: () => appConfiguration.getEndpoint()
  useBinaryFormat: true,
  credentials: "include",
  interceptors: [],
});
```

and able to override `baseUrl` in each request call
```

const res = await client.say({
  sentence: "I feel happy.",
}, {
   headers: overrideHeaders
   baseUrl: () => "overrideURL"
});
```
**Please specify whether the request is for Connect for Web or Connect for Node.js.**
Web

**Describe alternatives you've considered**
My workaround was to just force re-create transport and whole services in each request call. because it is hard to know when the baseUrl will be change

**Additional context**
N/A

**Comment by timostamm** [comment]
Hey Thu Vo 👋, creating a Transport on the fly is completely fine. In our [documentation for managing clients and transports](https://connect.build/docs/web/using-clients#managing-clients-and-transports), we create a small helper function to get a client. You can adapt it to create a new Transport if the `baseUrl` changes, for example:

```ts
import type { ServiceType } from "@bufbuild/protobuf";
import { type PromiseClient, createPromiseClient } from "@bufbuild/connect";
import { createGrpcWebTransport } from "@bufbuild/connect-web";
import { useMemo } from "react";

export function useClient<T extends ServiceType>(service: T): PromiseClient<T> {
  const baseUrl = appConfiguration.getEndpoint();
  return useMemo(() => {
    const transport = createGrpcWebTransport({
      baseUrl: baseUrl,
      useBinaryFormat: true,
      credentials: "include",
      interceptors: [],
    });
    return createPromiseClient(service, transport);
  }, [service, baseUrl]);
}
```

Another option is to use an [interceptor](https://connect.build/docs/web/interceptors) to modify the request URL just when a request is made. 

Changing the `baseUrl` option to also accept a function is a great idea, but we prefer to keep the options simple.

**Comment by vctqs1** [comment]
@timostamm, thank you. If creating a new client every time the URL changes is acceptable, then I believe we should stick with the current approach. 

Please let me know when it is available for change, or if I have the opportunity, I would also like to contribute. Thank you.
