### ISSUE TITLE
New streams cannot be created after receiving a GOAWAY

### ISSUE THREAD

**Issue by jacobwgillespie** [bufbuild/connect-es#680]
**Describe the bug**

We have an application that uses a connect Node.js client get itself stuck where every call to the connect client threw the error:

```
[internal] New streams cannot be created after receiving a GOAWAY
```

It appears that before the service got into this state, it also logged the following error:

```
[invalid_argument] protocol error: missing EndStreamResponse
```

I'm not particularly familiar with what's happening here on a protocol level, but would expect the Connect client to somehow detect broken connections and re-establish them. But in this case, the error state never recovers, and we have to restart the process to fix.

**To Reproduce**

I'm unsure how to reproduce. It's not happening on a regular interval (i.e. it's not happening every 10 minutes, the max request duration of the upstream server), it's gotten stuck maybe 4 times in the last day.

**Environment (please complete the following information):**

* Client-side (where the error occurs)
  - @bufbuild/connect-node version: `0.10.0`
  - Node.js version: `v18.16.0`
* Server-side
  - @bufbuild/connect-node version: `0.10.0`
  - Node.js version: `v18.16.0`

We create the client with the following code:

```typescript
const headerInterceptor: Interceptor = (next) => async (req) => {
  req.header.set('User-Agent', `...`)
  return await next(req)
}

const transport = createConnectTransport({
  httpVersion: '2',
  baseUrl: '...',
  interceptors: [headerInterceptor],
})

export const client = createPromiseClient(CloudService, transport)
```

**Additional context**

The client is making both client streaming and server streaming requests, in addition to unary requests.

We host our API in Google Cloud Run, serving http2. It has a max request duration of 10 minutes, so after 10 minutes the upstream API server will disconnect, however we are not seeing this error every 10 minutes, i.e. just having the upstream disconnect isn't enough for the client to get stuck.

**Comment by jacobwgillespie** [comment]
Thanks for the reply - we're working around this at the moment by try-catching the error and recreating the promise client if we get a `GOAWAY`, which appears to work for now, but we can downgrade if that mitigation doesn't hold.

I'm not sure if it's related, but is it expected that `sessionManager.abort(err)` would also re-establish a new connection? My initial reading of the code was that if we called `abort(err)`, that would place it into that transient error state and `gotoReady()` would recreate a new connection, but in practice that just changed the error message to `ConnectError: [internal] The session has been destroyed`. 

I could be misunderstanding what `abort()` should do, but perhaps that's related to the underlying issue.

**Comment by timostamm** [comment]
That's correct - calling `abort()` on `Http2SessionManager` should forcefully close all connections and streams. `state()` should return `"error"` or `"closed"` afterwards. A new request should then open a new connection (via `goToReady`).

It's used heavily in our tests and we have not seen any issues with it, but it seems likely that the session manager is put into a broken state by not receiving some expected events.

I can reproduce the issue ("New streams cannot be created..."). A fix should be out tomorrow.

**Comment by jeanp413** [comment]
Also hitting this, looking forward for the fix :pray:

**Comment by jacobwgillespie** [comment]
Awesome, thank you! 🎉

**Comment by jeanp413** [comment]
@timostamm I still get this error after updating to latest version, node version 16.17.1
```
ConnectError: [internal] New streams cannot be created after receiving a GOAWAY
	at i.from (\out\extension.js:2:1821526)
	at t.connectErrorFromNodeReason (\out\extension.js:2:1806365)
	at Promise.reject (\out\extension.js:2:1810858)
	at \out\extension.js:2:1812978
```

**Comment by jacobwgillespie** [comment]
> but `missing EndStreamResponse` may have been an unrelated problem. Let us know if you are still encountering either

I am still seeing this in the logs periodically, FYI. I'm not sure if it's harming anything, but FWIW it's still happening.

**Comment by timostamm** [comment]
Same report about still seeing the error: https://github.com/bufbuild/connect-es/issues/683#issuecomment-1606842932

We have not been able to reproduce this issue in any Node version. We will need a reproducible case or more detailed information about the code path to make a deliberate fix. @jeanp413, @akosyakov, since you are still seeing the issue in your logs, perhaps either of you is willing to run a version with tracing? I've sent an e-mail to both of you.

**Comment by akosyakov** [comment]
We cannot reproduce the issue on our side, only via automated error reporting from users. We won't have access to full logs, only errors.

**Comment by mustard-mh** [comment]
Hey @timostamm, we created a PR https://github.com/bufbuild/connect-es/pull/712, patch seems resolved this issue
