### ISSUE TITLE
ETIMEDOUT is reported as internal

### ISSUE THREAD

**Issue by akosyakov** [bufbuild/connect-es#682]
version: 0.10.0

```
ConnectError: [internal] read ETIMEDOUT
	at i.from (/out/extension.js:2:1820120)
	at t.connectErrorFromNodeReason (/out/extension.js:2:1804959)
	at Promise.reject (/out/extension.js:2:1809452)
	at ClientHttp2Stream.<anonymous> (/out/extension.js:2:1811449)
	at ClientHttp2Stream.emit (node:events:513:28)
	at emitErrorNT (node:<REDACTED: user-file-path>:157:8)
	at emitErrorCloseNT (node:<REDACTED: user-file-path>:122:3)
	at process.processTicksAndRejections (node:<REDACTED: user-file-path>:83:21)
```

grpc-node reports it as unavailable: https://github.com/grpc/grpc-node/blob/186718cb70af708c75584909b21169289d7363b2/packages/grpc-js/src/subchannel-call.ts#L243

**Comment by timostamm** [comment]
From the [Node.js documentation](https://nodejs.org/api/errors.html#common-system-errors):

> ETIMEDOUT (Operation timed out): A connect or send request failed because the connected party did not properly respond after a period of time.

Mapping to Unavailable seems reasonable. Do you know what the underlying issue was?

**Comment by akosyakov** [comment]
Unfortunately it is from our extension error telemetry. I can only assume that it is some user network issue.

**Comment by akosyakov** [comment]
Original stack frame here:
```
i.from at ../node_modules/@bufbuild/connect/dist/cjs/connect-error.js:73:19
from at ../node_modules/@bufbuild/connect-node/dist/cjs/node-error.js:54:38
reason at ../node_modules/@bufbuild/connect-node/dist/cjs/node-universal-client.js:305:110
reject at ../node_modules/@bufbuild/connect-node/dist/cjs/node-universal-client.js:194:21
ClientHttp2Stream.emit at null:null:null
emitErrorNT (node:<REDACTED: at null:null:null
emitErrorCloseNT (node:<REDACTED: at null:null:null
process.processTicksAndRejections (node:<REDACTED: at null:null:null
```

so it came from here: https://github.com/bufbuild/connect-es/blob/76b17edbbc4c0d4c98d1de8eb754192835458054/packages/connect-node/src/node-universal-client.ts#L328

**Comment by timostamm** [comment]
Thanks for the stack trace and the PR, @akosyakov. Fixed by https://github.com/bufbuild/connect-es/pull/686.
