### ISSUE TITLE
Support SSE for server-side streaming in connect protocol

### ISSUE THREAD

**Issue by StarpTech** [bufbuild/connect-es#690]
**Is your feature request related to a problem? Please describe.**

Currently, if you open a stream from the web to a Node.js server, it does long-polling, holding a connection open to stream the data.
Modern browsers support SSE to stream unidirectional data efficiently to the browser. Another big benefit of SSE is that it can be easily debugged in the browser with the developer tools.

> Server-Sent Events on the other hand, have been designed from the ground up to be efficient. When communicating using SSEs, a server can push data to your app whenever it wants, without the need to make an initial request. In other words, updates can be streamed from server to client as they happen. SSEs open a single unidirectional channel between server and client.

> The main difference between Server-Sent Events and long-polling is that SSEs are handled directly by the browser and the user simply has to listen for messages.

_Ref: https://web.dev/eventsource-basics/_

Downside: It does not support binary data.

**Describe the solution you'd like**
Extend the protocol and support it via flag in `createConnectTransport`.

Please specify whether the request is for Connect for Web or Connect for
Node.js.

Both.

**Describe alternatives you've considered**

**Additional context**
Related: https://github.com/bufbuild/connect-es/issues/366

- https://shopify.engineering/server-sent-events-data-streaming
- https://web.dev/eventsource-basics/

**Comment by timostamm** [comment]
Hey Dustin, thank you for opening the issue 👋 

On the wire, SSE and Connect streaming are actually very similar. They can both be long running connections, with zero or more messages in the body. In SSE, events are delimited by two newline characters after a message. In the Connect protocol, they are delimited by a length-prefix. 

SSE certainly has some nice properties, like the built-in retry and support in the browser network inspector. But they are designed for small textual payloads, which makes them less suitable for Connect. Besides the limitation regarding binary data (which you already noted), it is also not possible to send application-specific headers with an `EventSource`, and requests always use `GET`, implying idempotency. 

For some use cases, it is definitely the right technology, but is it really the right call to make it part of the protocol, considering the limitations? We are keeping a close eye on all technologies available, but we are also very interested in keeping the protocol lean and easy to implement. My recommendation would be to implement an application-specific [Transport](https://github.com/bufbuild/connect-es/blob/f8c12b82045f6ee52b5602ce4f9340f0ca7d21a9/packages/connect/src/transport.ts#L29) that uses SSE for server-streaming. This gives you wiggle room regarding the shortcomings, and you can still benefit from a type-safe API schema.

**Comment by StarpTech** [comment]
I'm going to close this.
