### ISSUE TITLE
How to get response type from any RPC implementation?

### ISSUE THREAD

**Issue by StarpTech** [bufbuild/connect-es#707]
**Describe the bug**

Hi, I'd like to get the type of the response payload of any RPC implementation to reuse it across my application. Example:

```ts
  return {
    helloWorld: async (ctx) => {
       return tryCatchLog<IneedThisType>(() => {   return ....  })
    },
}
```

I can't use the auto-generated `HelloWorldResponse` type. It is not compatible.

**Environment (please complete the following information):**
- @bufbuild/connect-node version: 0.10.1
- Node.js version: 18 LTS

**Additional context**

**Comment by StarpTech** [comment]
Found it https://github.com/bufbuild/protobuf-es/blob/main/docs/runtime_api.md#plainmessage
Example
```ts
import { PlainMessage } from "@bufbuild/protobuf";
PlainMessage<CreateFederatedSubgraphResponse>
```

**Comment by StarpTech** [comment]
Found it https://github.com/bufbuild/protobuf-es/blob/main/docs/runtime_api.md#plainmessage
Example
```ts
import { PlainMessage } from "@bufbuild/protobuf";
PlainMessage<CreateFederatedSubgraphResponse>
```

**Comment by smaye81** [comment]
@StarpTech going to close this, but if you have any other issues, feel free to open a new issue.
