### ISSUE TITLE
Guide: How to upload a file of any size?

### ISSUE THREAD

**Issue by StarpTech** [bufbuild/connect-es#709]
**Is your feature request related to a problem? Please describe.**

Hi, I couldn't find anything about file handling in the docs. How can we upload a file with the connect protocol? I can use `bytes` as a type in the proto, and it works, but I think it has limits.

More info:

I used Client Streaming to upload a file from Node.js to Node.js but how about Web? According to https://github.com/bufbuild/connect-es/issues/669 Client Streaming can't be supported yet.

Thank you in advance.

**Comment by smaye81** [comment]
Going to close this in favor of https://github.com/bufbuild/connect-es/issues/669 since both are interrelated.
