### ISSUE TITLE
wrong git tag for v0.12.0

### ISSUE THREAD

**Issue by felschr** [bufbuild/connect-es#755]
**Describe the bug**

I just realised that the git tag for GitHub release v0.12.0 is v0.11.1:
https://github.com/bufbuild/connect-es/releases/tag/v0.11.1

**Comment by timostamm** [comment]
Thanks for the shout, @felschr. The tag pointed to the right commit, but was named incorrectly. Fixed up: https://github.com/bufbuild/connect-es/releases/tag/v0.12.0
